# This is a minimal config.toml file with the updated settings based on the diff
# You may need to add more sections and settings based on your specific requirements

[auth]
enabled = true
site_url = "mydavids.com"
additional_redirect_urls = ["https://web-analytics-c444rters-projects.vercel.app/", "https://web-analytics-c444rters-projects.vercel.app/**", "https://web-*-analytics-c444rters-projects.vercel.app", "https://web-*-analytics-c444rters-projects.vercel.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400
[auth.email.template]
[auth.sms]
enable_signup = false
