[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
# No additional build commands

[deploy]
startCommand = "web"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
