version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_dashboard
    ports:
      - "5432:5432"
  
  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/analytics_dashboard

    depends_on:
      - db
