services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_davids
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/my_davids
      SECRET_KEY: "YOUR_SECRET_KEY"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
    volumes:
      - ./uploads:/app/uploads    # <-- Share uploads
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: rq worker --with-scheduler --url redis://default:WmfTavIVEnHSxGgrjKDPkIWuFwGeDjwp@interchange.proxy.rlwy.net:35531 --name worker-local --verbose --worker-ttl 3600 --job-timeout 3600 --burst-delay 1 --max-jobs 0
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/my_davids
      SECRET_KEY: "YOUR_SECRET_KEY"
      REDIS_HOST: interchange.proxy.rlwy.net
      REDIS_PORT: "35531"
      REDIS_DB: "0"
      REDIS_PASSWORD: "WmfTavIVEnHSxGgrjKDPkIWuFwGeDjwp"
      REDIS_USERNAME: "default"
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
    volumes:
      - ./uploads:/app/uploads    # <-- Share uploads
    depends_on:
      - db

volumes:
  postgres_data:
