[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[deploy]
startCommand = "cd backend && rq worker --with-scheduler --host ${REDISHOST} --port ${REDISPORT} --password ${REDISPASSWORD} --name worker-${RAILWAY_SERVICE_ID:-local} --verbose --worker-ttl 3600 --results-ttl 3600 --max-jobs 0 default"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
