# Main API service configuration
[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 8000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Worker service configuration
[build.worker]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy.worker]
startCommand = "rq worker --with-scheduler --url redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB} --name worker-${RAILWAY_SERVICE_ID} --verbose --worker-ttl 3600 --job-timeout 3600 --burst-delay 1 --max-jobs 0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
envs = { OBJC_DISABLE_INITIALIZE_FORK_SAFETY = "YES" }

# Migrations service configuration
[build.migrations]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy.migrations]
startCommand = "alembic upgrade head"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
