# Main API service configuration
[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 8000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Worker service configuration
[build.worker]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy.worker]
startCommand = "rq worker --with-scheduler"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
envs = { OBJC_DISABLE_INITIALIZE_FORK_SAFETY = "YES" }

# Migrations service configuration
[build.migrations]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy.migrations]
startCommand = "alembic upgrade head"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
