"""Add upload_id to orders

Revision ID: 0084c7558f73
Revises: f1553950c6ff
Create Date: 2025-03-17 18:09:21.378912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0084c7558f73'
down_revision: Union[str, None] = 'f1553950c6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'uploads', ['upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'upload_id')
    # ### end Alembic commands ###
