"""Add line_items table and update orders table

Revision ID: 37c485a93436
Revises: b18df65bc4c6
Create Date: 2025-03-12 17:26:34.767510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c485a93436'
down_revision: Union[str, None] = 'b18df65bc4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('lineitem_quantity', sa.Integer(), nullable=True),
    sa.Column('lineitem_name', sa.String(), nullable=True),
    sa.Column('lineitem_price', sa.String(), nullable=True),
    sa.Column('lineitem_compare_at_price', sa.String(), nullable=True),
    sa.Column('lineitem_sku', sa.String(), nullable=True),
    sa.Column('lineitem_requires_shipping', sa.String(), nullable=True),
    sa.Column('lineitem_taxable', sa.String(), nullable=True),
    sa.Column('lineitem_fulfillment_status', sa.String(), nullable=True),
    sa.Column('lineitem_discount', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_id'), 'line_items', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.drop_column('orders', 'tax_1_name')
    op.drop_column('orders', 'lineitem_name')
    op.drop_column('orders', 'tax_4_name')
    op.drop_column('orders', 'lineitem_sku')
    op.drop_column('orders', 'lineitem_compare_at_price')
    op.drop_column('orders', 'tax_2_name')
    op.drop_column('orders', 'lineitem_quantity')
    op.drop_column('orders', 'lineitem_fulfillment_status')
    op.drop_column('orders', 'lineitem_taxable')
    op.drop_column('orders', 'tax_2_value')
    op.drop_column('orders', 'lineitem_price')
    op.drop_column('orders', 'tax_3_name')
    op.drop_column('orders', 'tax_4_value')
    op.drop_column('orders', 'lineitem_requires_shipping')
    op.drop_column('orders', 'lineitem_discount')
    op.drop_column('orders', 'tax_5_value')
    op.drop_column('orders', 'tax_5_name')
    op.drop_column('orders', 'tax_3_value')
    op.drop_column('orders', 'tax_1_value')
    op.drop_column('orders', 'note_attributes')
    op.drop_column('orders', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('note_attributes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_1_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_3_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_5_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_5_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_discount', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_requires_shipping', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_4_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_3_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_price', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_2_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_taxable', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_fulfillment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_2_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_compare_at_price', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_4_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lineitem_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_1_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_line_items_id'), table_name='line_items')
    op.drop_table('line_items')
    # ### end Alembic commands ###
