"""Add file_size column to uploads and update auth fields

Revision ID: 3c0afff22841
Revises: 5ad5170c537b
Create Date: 2025-03-11 19:49:24.448832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0afff22841'
down_revision: Union[str, None] = '5ad5170c537b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
