"""Add file_size column to uploads

Revision ID: 5ad5170c537b
Revises: 2391fbb8337c
Create Date: 2025-03-11 19:38:24.641091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad5170c537b'
down_revision: Union[str, None] = '2391fbb8337c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_size', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'file_size')
    # ### end Alembic commands ###
