"""in depth analytics

Revision ID: 5b09189040db
Revises: 49408e542447
Create Date: 2025-04-09 07:45:24.000253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b09189040db'
down_revision: Union[str, None] = '49408e542447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('total_rows', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('records_processed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'records_processed')
    op.drop_column('uploads', 'total_rows')
    # ### end Alembic commands ###
