"""add_ml_projections_and_test_data_support

Revision ID: a76a60be9b13
Revises: f43b12302d22
Create Date: 2025-04-30 11:35:25.843757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76a60be9b13'
down_revision: Union[str, None] = 'f43b12302d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL with USING clause to properly convert VARCHAR to NUMERIC
    op.execute("ALTER TABLE line_items ALTER COLUMN lineitem_price TYPE NUMERIC(12, 2) USING CASE WHEN lineitem_price ~ '^[0-9]+(\.[0-9]+)?$' THEN lineitem_price::NUMERIC(12, 2) ELSE NULL END")
    op.execute("ALTER TABLE line_items ALTER COLUMN lineitem_compare_at_price TYPE NUMERIC(12, 2) USING CASE WHEN lineitem_compare_at_price ~ '^[0-9]+(\.[0-9]+)?$' THEN lineitem_compare_at_price::NUMERIC(12, 2) ELSE NULL END")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('line_items', 'lineitem_compare_at_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('line_items', 'lineitem_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
