"""refined uploads, processing file types, accessing order data

Revision ID: b18df65bc4c6
Revises: 3c0afff22841
Create Date: 2025-03-12 17:01:29.957629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18df65bc4c6'
down_revision: Union[str, None] = '3c0afff22841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('financial_status', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('fulfillment_status', sa.String(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('accepts_marketing', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('subtotal', sa.String(), nullable=True),
    sa.Column('shipping', sa.String(), nullable=True),
    sa.Column('taxes', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('discount_code', sa.String(), nullable=True),
    sa.Column('discount_amount', sa.String(), nullable=True),
    sa.Column('shipping_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lineitem_quantity', sa.Integer(), nullable=True),
    sa.Column('lineitem_name', sa.String(), nullable=True),
    sa.Column('lineitem_price', sa.String(), nullable=True),
    sa.Column('lineitem_compare_at_price', sa.String(), nullable=True),
    sa.Column('lineitem_sku', sa.String(), nullable=True),
    sa.Column('lineitem_requires_shipping', sa.String(), nullable=True),
    sa.Column('lineitem_taxable', sa.String(), nullable=True),
    sa.Column('lineitem_fulfillment_status', sa.String(), nullable=True),
    sa.Column('billing_name', sa.String(), nullable=True),
    sa.Column('billing_street', sa.String(), nullable=True),
    sa.Column('billing_address1', sa.String(), nullable=True),
    sa.Column('billing_address2', sa.String(), nullable=True),
    sa.Column('billing_company', sa.String(), nullable=True),
    sa.Column('billing_city', sa.String(), nullable=True),
    sa.Column('billing_zip', sa.String(), nullable=True),
    sa.Column('billing_province', sa.String(), nullable=True),
    sa.Column('billing_country', sa.String(), nullable=True),
    sa.Column('billing_phone', sa.String(), nullable=True),
    sa.Column('shipping_name', sa.String(), nullable=True),
    sa.Column('shipping_street', sa.String(), nullable=True),
    sa.Column('shipping_address1', sa.String(), nullable=True),
    sa.Column('shipping_address2', sa.String(), nullable=True),
    sa.Column('shipping_company', sa.String(), nullable=True),
    sa.Column('shipping_city', sa.String(), nullable=True),
    sa.Column('shipping_zip', sa.String(), nullable=True),
    sa.Column('shipping_province', sa.String(), nullable=True),
    sa.Column('shipping_country', sa.String(), nullable=True),
    sa.Column('shipping_phone', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('note_attributes', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('refunded_amount', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('outstanding_balance', sa.String(), nullable=True),
    sa.Column('employee', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('lineitem_discount', sa.String(), nullable=True),
    sa.Column('tax_1_name', sa.String(), nullable=True),
    sa.Column('tax_1_value', sa.String(), nullable=True),
    sa.Column('tax_2_name', sa.String(), nullable=True),
    sa.Column('tax_2_value', sa.String(), nullable=True),
    sa.Column('tax_3_name', sa.String(), nullable=True),
    sa.Column('tax_3_value', sa.String(), nullable=True),
    sa.Column('tax_4_name', sa.String(), nullable=True),
    sa.Column('tax_4_value', sa.String(), nullable=True),
    sa.Column('tax_5_name', sa.String(), nullable=True),
    sa.Column('tax_5_value', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.Column('duties', sa.String(), nullable=True),
    sa.Column('billing_province_name', sa.String(), nullable=True),
    sa.Column('shipping_province_name', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('payment_terms_name', sa.String(), nullable=True),
    sa.Column('next_payment_due_at', sa.DateTime(), nullable=True),
    sa.Column('payment_references', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
