"""Add variant_id column to line_items

Revision ID: f1553950c6ff
Revises: 37c485a93436
Create Date: 2025-03-17 17:11:08.970218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1553950c6ff'
down_revision: Union[str, None] = '37c485a93436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('variant_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'variant_id')
    # ### end Alembic commands ###
