"""Add upload_id to orders

Revision ID: 22dba09067a0
Revises: 0084c7558f73
Create Date: 2025-03-17 18:40:14.844003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dba09067a0'
down_revision: Union[str, None] = '0084c7558f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'status')
    # ### end Alembic commands ###
