"""in depth analytics

Revision ID: 31a87cee84b2
Revises: ec76c8f07681
Create Date: 2025-04-09 08:54:56.332069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a87cee84b2'
down_revision: Union[str, None] = 'ec76c8f07681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('job_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'job_id')
    # ### end Alembic commands ###
